name: Build and Deploy API

on:
  pull_request:
    types: [closed]
    branches: [master]
  workflow_dispatch:

# Evita execuções duplicadas simultâneas na mesma ref
concurrency:
  group: corretorapi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'develop')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore MeuCorretorApi.sln

      - name: Build
        run: dotnet build MeuCorretorApi.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish MeuCorretorApi/MeuCorretorApi.csproj -c Release -o publish --no-build

      # Login opcional via Service Principal (JSON) se secret AZURE_CREDENTIALS existir
      - name: Azure Login (opcional)
        if: ${{ secrets.AZURE_CREDENTIALS != '' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validar secret Publish Profile
        run: |
          if [ -z "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" ]; then
            echo 'ERRO: Secret AZURE_WEBAPP_PUBLISH_PROFILE não configurado. Adicione o conteúdo XML completo do Publish Profile às secrets.'
            exit 1
          fi
          if [ -z "${{ secrets.AZURE_WEBAPP_NAME }}" ]; then
            echo 'ERRO: Secret AZURE_WEBAPP_NAME não configurado.'
            exit 1
          fi

      - name: Deploy to Azure WebApp (Publish Profile)
        if: ${{ success() && secrets.AZURE_WEBAPP_PUBLISH_PROFILE != '' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish

      - name: Deploy to Azure WebApp (Credenciais SP) - Fallback
        if: ${{ success() && secrets.AZURE_WEBAPP_PUBLISH_PROFILE == '' && secrets.AZURE_CREDENTIALS != '' }}
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: publish

      - name: Post Subscription Disabled Warning
        if: failure()
        run: |
          echo 'Falha no deploy. Se código 409: assinatura Azure desabilitada ou sem permissão. Verifique billing e SP.'
